[unstable]
bindeps = true  # 允许build.rs使用kernel编译好的二进制文件
json-target-spec = true # 允许使用.json文件自定义target
unstable-options = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner" # 使用cargo run时调用bootimage启动qemu

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[registries.ustc]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[net]
git-fetch-with-cli = true